### ISSUE TITLE
Missed example code

### ISSUE THREAD

**Issue by silk0vsky** [aws-samples/skiresort-example-dynamodb-aws-sdk-v1#1]
Hi @arjanschaaf . Looks like there are missed files in this repo. I can't find the actual example of DynamoDB sdk API usage. Your [blogpost](https://aws.amazon.com/blogs/database/amazon-dynamodb-single-table-design-using-dynamodbmapper-and-spring-boot/) mentions code:

```
List<LiftDynamicStats> results = mapper.query(LiftDynamicStats.class,
        new DynamoDBQueryExpression<LiftDynamicStats>()
                .withConsistentRead(false)
                .withExpressionAttributeValues(
                        Map.of(":val1", new AttributeValue().withS("LIFT#" + lift1)))
                .withIndexName("GSI_1")
                .withKeyConditionExpression("GSI_1_PK = :val1"));
```

Which is missed in repository.

**Comment by arjanschaaf** [comment]
Hi @silk0vsky,

Thank you for reaching out! I think the code does exists, I put it in a test class. Because the project itself does really contain any functionality, I created some test cases that expressed the access pattern I wanted to use in the blog:

https://github.com/aws-samples/skiresort-example-dynamodb-aws-sdk-v1/blob/1853051bf6cf39a42bdd923c02650bf0f525d28f/src/test/java/com/aws/samples/skiresort/test/GlobalSecondaryIndexTestIT.java#L96

**Comment by silk0vsky** [comment]
My bad. Thanks for you work!
